/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/jah_db.o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/jah_db.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_8ZvwQIddfpj2THRVPsFzIQ[1];
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA {
char dummy;
};
N_NIMCALL(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*, open_SRJkmN7JR2aulOhbafCrYA)(NimStringDesc* connection, NimStringDesc* user, NimStringDesc* password, NimStringDesc* database);
N_NIMCALL(void, exec_kASFnJjvwTJpKpmn9aQHmPg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(void, close_yRzNipQFOsKqLVySy7Je9bw_2)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3Init000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_commonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_commonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, jah_dbDatInit000)(void);
tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db_mGVHccK3U9aAs6NRgO9aHP9cQ;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_Ag7ePA3FpL9cNsKq6eSdpOg_2, "normanpd.db", 11);
STRING_LITERAL(TM_Ag7ePA3FpL9cNsKq6eSdpOg_3, "", 0);
STRING_LITERAL(TM_Ag7ePA3FpL9cNsKq6eSdpOg_4, "CREATE TABLE CrimeReport (\012    arrest_time TEXT,\012    case_numbe"
"r TEXT,\012    arrest_location TEXT,\012    offense TEXT,\012    arrestee"
"_name TEXT,\012    arrestee_birthday TEXT,\012    city TEXT,\012    state"
" TEXT,\012    zip TEXT,\012    status TEXT,\012    officer TEXT)", 246);
STRING_LITERAL(TM_Ag7ePA3FpL9cNsKq6eSdpOg_5, "CREATE TABLE Incident (\012    incident_number TEXT,\012    location "
"TEXT,\012    nature TEXT,\012    incident_ori TEXT\012)", 109);
STRING_LITERAL(TM_Ag7ePA3FpL9cNsKq6eSdpOg_6, "create table Officer ( \012    caseno TEXT,\012    dateno TEXT,\012    n"
"amelabel TEXT,\012    locationlabel TEXT,\012    chargelabel TEXT\012 )", 125);
STRING_LITERAL(TM_Ag7ePA3FpL9cNsKq6eSdpOg_7, "create table Criminal ( \012    caseno TEXT,\012    dateofarrest TEXT"
",\012    nameofarrest TEXT,\012    dateofbirth TEXT,\012    charge TEXT\012 "
")", 128);

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_sqlite3DatInit000();
	stdlib_db_commonDatInit000();
	stdlib_db_sqliteDatInit000();
	jah_dbDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_sqlite3Init000();
	stdlib_db_commonInit000();
	stdlib_db_sqliteInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T1_;
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T2_;
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T3_;
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T4_;
	nimfr_("jah_db", "jah_db.nim");
	nimln_(3, "jah_db.nim");
	db_mGVHccK3U9aAs6NRgO9aHP9cQ = open_SRJkmN7JR2aulOhbafCrYA(((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_2), ((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_3), ((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_3), ((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_3));
	nimln_(6, "jah_db.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_mGVHccK3U9aAs6NRgO9aHP9cQ, ((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_4), T1_, 0);
	nimln_(19, "jah_db.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_mGVHccK3U9aAs6NRgO9aHP9cQ, ((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_5), T2_, 0);
	nimln_(26, "jah_db.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_mGVHccK3U9aAs6NRgO9aHP9cQ, ((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_6), T3_, 0);
	nimln_(34, "jah_db.nim");
	memset((void*)T4_, 0, sizeof(T4_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_mGVHccK3U9aAs6NRgO9aHP9cQ, ((NimStringDesc*) &TM_Ag7ePA3FpL9cNsKq6eSdpOg_7), T4_, 0);
	nimln_(42, "jah_db.nim");
	close_yRzNipQFOsKqLVySy7Je9bw_2(db_mGVHccK3U9aAs6NRgO9aHP9cQ);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, jah_dbDatInit000)(void) {
}

