/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/stdlib_sqlite3.o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/stdlib_sqlite3.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
typedef struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, tyProc_MGvm2GDOLe9cOGVrF2xiL8g) (NCSTRING filename, tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA** ppDb);
typedef N_CDECL_PTR(NCSTRING, tyProc_9c803Jlmvw39cDHXPnE9c9acPA) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* para1);
typedef N_CDECL_PTR(int, tyProc_EhxAId0fqbb7y09bLz1RLng) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NCSTRING zSql, int nByte, tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw** ppStmt, NCSTRING* pzTail);
typedef N_CDECL_PTR(NI32, tyProc_Fhopq8qsQV4lYKX3MLNyKQ) (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1);
typedef N_CDECL_PTR(NI32, tyProc_gjdebP9bh9a6kXA5fmIpsLzQ) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* para1);
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA {
char dummy;
};
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw {
char dummy;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_ZpuQ9cIusnUOv1iEoFq9arZw_2;
tyProc_MGvm2GDOLe9cOGVrF2xiL8g Dl_122521_;
tyProc_9c803Jlmvw39cDHXPnE9c9acPA Dl_122534_;
tyProc_EhxAId0fqbb7y09bLz1RLng Dl_122549_;
tyProc_Fhopq8qsQV4lYKX3MLNyKQ Dl_122665_;
tyProc_Fhopq8qsQV4lYKX3MLNyKQ Dl_122707_;
tyProc_gjdebP9bh9a6kXA5fmIpsLzQ Dl_122415_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_ZpuQ9cIusnUOv1iEoFq9arZw_4, "libsqlite3.so", 13);
STRING_LITERAL(TM_ZpuQ9cIusnUOv1iEoFq9arZw_6, "libsqlite3.so.0", 15);
STRING_LITERAL(TM_ZpuQ9cIusnUOv1iEoFq9arZw_7, "libsqlite3.so(|.0)", 18);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3Init000)(void) {
	nimfr_("sqlite3", "sqlite3.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3DatInit000)(void) {
if (!((TM_ZpuQ9cIusnUOv1iEoFq9arZw_2 = nimLoadLibrary((NimStringDesc*) &TM_ZpuQ9cIusnUOv1iEoFq9arZw_4))
||(TM_ZpuQ9cIusnUOv1iEoFq9arZw_2 = nimLoadLibrary((NimStringDesc*) &TM_ZpuQ9cIusnUOv1iEoFq9arZw_6))
)) nimLoadLibraryError((NimStringDesc*) &TM_ZpuQ9cIusnUOv1iEoFq9arZw_7);
	Dl_122521_ = (tyProc_MGvm2GDOLe9cOGVrF2xiL8g) nimGetProcAddr(TM_ZpuQ9cIusnUOv1iEoFq9arZw_2, "sqlite3_open");
	Dl_122534_ = (tyProc_9c803Jlmvw39cDHXPnE9c9acPA) nimGetProcAddr(TM_ZpuQ9cIusnUOv1iEoFq9arZw_2, "sqlite3_errmsg");
	Dl_122549_ = (tyProc_EhxAId0fqbb7y09bLz1RLng) nimGetProcAddr(TM_ZpuQ9cIusnUOv1iEoFq9arZw_2, "sqlite3_prepare_v2");
	Dl_122665_ = (tyProc_Fhopq8qsQV4lYKX3MLNyKQ) nimGetProcAddr(TM_ZpuQ9cIusnUOv1iEoFq9arZw_2, "sqlite3_step");
	Dl_122707_ = (tyProc_Fhopq8qsQV4lYKX3MLNyKQ) nimGetProcAddr(TM_ZpuQ9cIusnUOv1iEoFq9arZw_2, "sqlite3_finalize");
	Dl_122415_ = (tyProc_gjdebP9bh9a6kXA5fmIpsLzQ) nimGetProcAddr(TM_ZpuQ9cIusnUOv1iEoFq9arZw_2, "sqlite3_close");
}

