/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/stdlib_db_sqlite.o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/stdlib_db_sqlite.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_DbError_w65gHFDlremRAyGJ4f6zkA tyObject_DbError_w65gHFDlremRAyGJ4f6zkA;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, tyProc_MGvm2GDOLe9cOGVrF2xiL8g) (NCSTRING filename, tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA** ppDb);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_DbError_w65gHFDlremRAyGJ4f6zkA {
  tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NCSTRING, tyProc_9c803Jlmvw39cDHXPnE9c9acPA) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* para1);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef N_CDECL_PTR(int, tyProc_EhxAId0fqbb7y09bLz1RLng) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NCSTRING zSql, int nByte, tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw** ppStmt, NCSTRING* pzTail);
typedef N_CDECL_PTR(NI32, tyProc_Fhopq8qsQV4lYKX3MLNyKQ) (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* para1);
typedef N_CDECL_PTR(NI32, tyProc_gjdebP9bh9a6kXA5fmIpsLzQ) (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* para1);
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA {
char dummy;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw {
char dummy;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(void, dbError_yRzNipQFOsKqLVySy7Je9bw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db) __attribute__((noreturn));
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, tryExec_Wy7WfNcrDtpQlAr7l6ZBZw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, dbFormat_4xitxSXjtmpEVS63UNhgwA)(NimStringDesc* formatstr, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, dbQuote_n8zdcw6t64ZGFNADbUlAfA)(NimStringDesc* s);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
extern tyProc_MGvm2GDOLe9cOGVrF2xiL8g Dl_122521_;
extern TNimType NTI_HDK9arR7eW5QkLI9bRSdsGnA_;
extern TNimType NTI_w65gHFDlremRAyGJ4f6zkA_;
extern tyProc_9c803Jlmvw39cDHXPnE9c9acPA Dl_122534_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern tyProc_EhxAId0fqbb7y09bLz1RLng Dl_122549_;
extern tyProc_Fhopq8qsQV4lYKX3MLNyKQ Dl_122665_;
extern tyProc_Fhopq8qsQV4lYKX3MLNyKQ Dl_122707_;
extern tyProc_gjdebP9bh9a6kXA5fmIpsLzQ Dl_122415_;
STRING_LITERAL(TM_Y7t52g9b69cVuzHT832OjgmA_2, "", 0);
STRING_LITERAL(TM_Y7t52g9b69cVuzHT832OjgmA_3, "NULL", 4);
STRING_LITERAL(TM_Y7t52g9b69cVuzHT832OjgmA_4, "\'", 1);
STRING_LITERAL(TM_Y7t52g9b69cVuzHT832OjgmA_5, "\'\'", 2);
STRING_LITERAL(TM_Y7t52g9b69cVuzHT832OjgmA_7, "len(a) == L string modified while iterating over it", 51);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(void, dbError_yRzNipQFOsKqLVySy7Je9bw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db) {
	tyObject_DbError_w65gHFDlremRAyGJ4f6zkA* e;
	NCSTRING T1_;
	nimfr_("dbError", "db_sqlite.nim");
	e = (tyObject_DbError_w65gHFDlremRAyGJ4f6zkA*)0;
	nimln_(102, "db_sqlite.nim");
	e = (tyObject_DbError_w65gHFDlremRAyGJ4f6zkA*) newObj((&NTI_HDK9arR7eW5QkLI9bRSdsGnA_), sizeof(tyObject_DbError_w65gHFDlremRAyGJ4f6zkA));
	(*e).Sup.Sup.Sup.Sup.m_type = (&NTI_w65gHFDlremRAyGJ4f6zkA_);
	nimln_(103, "db_sqlite.nim");
	T1_ = (NCSTRING)0;
	T1_ = Dl_122534_(db);
	asgnRefNoCycle((void**) (&(*e).Sup.Sup.Sup.message), cstrToNimstr(T1_));
	nimln_(104, "db_sqlite.nim");
	raiseException((Exception*)e, "DbError");
	popFrame();
}

N_NIMCALL(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*, open_SRJkmN7JR2aulOhbafCrYA)(NimStringDesc* connection, NimStringDesc* user, NimStringDesc* password, NimStringDesc* database) {
	tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* result;
	tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db;
	nimfr_("open", "db_sqlite.nim");
	result = (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*)0;
	db = (tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*)0;
	nimln_(304, "db_sqlite.nim");
	{
		NI32 T3_;
		T3_ = (NI32)0;
		T3_ = Dl_122521_(connection->data, &db);
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		nimln_(305, "db_sqlite.nim");
		result = db;
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(307, "db_sqlite.nim");
		dbError_yRzNipQFOsKqLVySy7Je9bw(db);
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NimStringDesc*, dbQuote_n8zdcw6t64ZGFNADbUlAfA)(NimStringDesc* s) {
	NimStringDesc* result;
	nimfr_("dbQuote", "db_sqlite.nim");
{	result = (NimStringDesc*)0;
	nimln_(108, "db_sqlite.nim");
	{
		if (!(s == 0)) goto LA3_;
		result = copyString(((NimStringDesc*) &TM_Y7t52g9b69cVuzHT832OjgmA_3));
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(109, "db_sqlite.nim");
	result = copyString(((NimStringDesc*) &TM_Y7t52g9b69cVuzHT832OjgmA_4));
	{
		NIM_CHAR c;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		nimln_(3657, "system.nim");
		i = ((NI) 0);
		nimln_(3658, "system.nim");
		L = (s ? s->Sup.len : 0);
		{
			nimln_(3659, "system.nim");
			while (1) {
				NI TM_Y7t52g9b69cVuzHT832OjgmA_6;
				if (!(i < L)) goto LA7;
				nimln_(3660, "system.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				c = s->data[i];
				nimln_(111, "db_sqlite.nim");
				{
					if (!((NU8)(c) == (NU8)(39))) goto LA10_;
					result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_Y7t52g9b69cVuzHT832OjgmA_5));
				}
				goto LA8_;
				LA10_: ;
				{
					nimln_(112, "db_sqlite.nim");
					result = addChar(result, c);
				}
				LA8_: ;
				nimln_(3661, "system.nim");
				TM_Y7t52g9b69cVuzHT832OjgmA_6 = addInt(i, ((NI) 1));
				i = (NI)(TM_Y7t52g9b69cVuzHT832OjgmA_6);
				nimln_(3662, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L))) goto LA15_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Y7t52g9b69cVuzHT832OjgmA_7));
				}
				LA15_: ;
			} LA7: ;
		}
	}
	nimln_(113, "db_sqlite.nim");
	result = addChar(result, 39);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, dbFormat_4xitxSXjtmpEVS63UNhgwA)(NimStringDesc* formatstr, NimStringDesc** args, NI argsLen_0) {
	NimStringDesc* result;
	NI a;
	nimfr_("dbFormat", "db_sqlite.nim");
	result = (NimStringDesc*)0;
	nimln_(116, "db_sqlite.nim");
	result = copyString(((NimStringDesc*) &TM_Y7t52g9b69cVuzHT832OjgmA_2));
	nimln_(117, "db_sqlite.nim");
	a = ((NI) 0);
	{
		NIM_CHAR c;
		NimStringDesc* colontmp_;
		NI i;
		NI L;
		c = (NIM_CHAR)0;
		colontmp_ = (NimStringDesc*)0;
		nimln_(118, "db_sqlite.nim");
		colontmp_ = formatstr;
		nimln_(3657, "system.nim");
		i = ((NI) 0);
		nimln_(3658, "system.nim");
		L = (colontmp_ ? colontmp_->Sup.len : 0);
		{
			nimln_(3659, "system.nim");
			while (1) {
				NI TM_Y7t52g9b69cVuzHT832OjgmA_9;
				if (!(i < L)) goto LA3;
				nimln_(3660, "system.nim");
				if ((NU)(i) > (NU)(colontmp_->Sup.len)) raiseIndexError();
				c = colontmp_->data[i];
				nimln_(119, "db_sqlite.nim");
				{
					NimStringDesc* T8_;
					NI TM_Y7t52g9b69cVuzHT832OjgmA_8;
					if (!((NU8)(c) == (NU8)(63))) goto LA6_;
					nimln_(120, "db_sqlite.nim");
					if ((NU)(a) >= (NU)(argsLen_0)) raiseIndexError();
					T8_ = (NimStringDesc*)0;
					T8_ = dbQuote_n8zdcw6t64ZGFNADbUlAfA(args[a]);
					result = resizeString(result, T8_->Sup.len + 0);
appendString(result, T8_);
					nimln_(121, "db_sqlite.nim");
					TM_Y7t52g9b69cVuzHT832OjgmA_8 = addInt(a, ((NI) 1));
					a = (NI)(TM_Y7t52g9b69cVuzHT832OjgmA_8);
				}
				goto LA4_;
				LA6_: ;
				{
					nimln_(123, "db_sqlite.nim");
					result = addChar(result, c);
				}
				LA4_: ;
				nimln_(3661, "system.nim");
				TM_Y7t52g9b69cVuzHT832OjgmA_9 = addInt(i, ((NI) 1));
				i = (NI)(TM_Y7t52g9b69cVuzHT832OjgmA_9);
				nimln_(3662, "system.nim");
				{
					if (!!(((colontmp_ ? colontmp_->Sup.len : 0) == L))) goto LA12_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Y7t52g9b69cVuzHT832OjgmA_7));
				}
				LA12_: ;
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_NIMCALL(NIM_BOOL, tryExec_Wy7WfNcrDtpQlAr7l6ZBZw)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0) {
	NIM_BOOL result;
	NimStringDesc* q;
	tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw* stmt;
	nimfr_("tryExec", "db_sqlite.nim");
	result = (NIM_BOOL)0;
	nimln_(129, "db_sqlite.nim");
	q = dbFormat_4xitxSXjtmpEVS63UNhgwA(query, args, argsLen_0);
	stmt = (tyObject_Tstmt_KEhcjAECDwKIYLLjIzakvw*)0;
	nimln_(131, "db_sqlite.nim");
	{
		int T3_;
		T3_ = (int)0;
		T3_ = Dl_122549_(db, q->data, ((int)chckRange((q ? q->Sup.len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))), &stmt, NIM_NIL);
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		nimln_(132, "db_sqlite.nim");
		{
			NI32 T8_;
			NI32 T11_;
			T8_ = (NI32)0;
			T8_ = Dl_122665_(stmt);
			if (!(T8_ == ((NI32) 101))) goto LA9_;
			nimln_(133, "db_sqlite.nim");
			T11_ = (NI32)0;
			T11_ = Dl_122707_(stmt);
			result = (T11_ == ((NI32) 0));
		}
		LA9_: ;
	}
	LA4_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, exec_kASFnJjvwTJpKpmn9aQHmPg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0) {
	nimfr_("exec", "db_sqlite.nim");
	nimln_(138, "db_sqlite.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = tryExec_Wy7WfNcrDtpQlAr7l6ZBZw(db, query, args, argsLen_0);
		if (!!(T3_)) goto LA4_;
		dbError_yRzNipQFOsKqLVySy7Je9bw(db);
	}
	LA4_: ;
	popFrame();
}

N_NIMCALL(void, close_yRzNipQFOsKqLVySy7Je9bw_2)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db) {
	nimfr_("close", "db_sqlite.nim");
	nimln_(297, "db_sqlite.nim");
	{
		NI32 T3_;
		nimln_(378, "system.nim");
		nimln_(297, "db_sqlite.nim");
		T3_ = (NI32)0;
		T3_ = Dl_122415_(db);
		if (!!((T3_ == ((NI32) 0)))) goto LA4_;
		dbError_yRzNipQFOsKqLVySy7Je9bw(db);
	}
	LA4_: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteInit000)(void) {
	nimfr_("db_sqlite", "db_sqlite.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteDatInit000)(void) {
}

