/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/toss_db.o /home/mulh8377/Courses/TextAnalyis/projects/cs5293-project0/project0/modules/Storage/nim/nimcache/toss_db.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_8ZvwQIddfpj2THRVPsFzIQ[1];
struct tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA {
char dummy;
};
N_NIMCALL(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA*, open_SRJkmN7JR2aulOhbafCrYA)(NimStringDesc* connection, NimStringDesc* user, NimStringDesc* password, NimStringDesc* database);
N_NIMCALL(void, exec_kASFnJjvwTJpKpmn9aQHmPg)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db, NimStringDesc* query, NimStringDesc** args, NI argsLen_0);
N_NIMCALL(void, close_yRzNipQFOsKqLVySy7Je9bw_2)(tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3Init000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sqlite3DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_commonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_commonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_db_sqliteDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, toss_dbDatInit000)(void);
tyObject_Sqlite3_xRZkbCqVWSKf8kX4o9cbKXA* db_pg1xfNAJINTuNjZ5I9bps6g;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_2, "normanpd.db", 11);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_3, "", 0);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_4, "DROP TABLE IF EXISTS OFFICER", 28);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_5, "table officer is gone", 21);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_6, "DROP TABLE IF EXISTS CRIMINAL", 29);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_7, "table criminal is gone", 22);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_8, "DROP TABLE IF EXISTS Incident", 29);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_9, "table Incident is gone", 22);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_10, "DROP TABLE IF EXISTS CrimeReport", 32);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_11, "table crimereport is gone", 25);
STRING_LITERAL(TM_OQVAKSQ5eImSrw9bNcanC6A_12, "database is closed", 18);

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_sqlite3DatInit000();
	stdlib_db_commonDatInit000();
	stdlib_db_sqliteDatInit000();
	toss_dbDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_sqlite3Init000();
	stdlib_db_commonInit000();
	stdlib_db_sqliteInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}


static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T1_;
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T2_;
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T3_;
	tyArray_8ZvwQIddfpj2THRVPsFzIQ T4_;
	nimfr_("toss_db", "toss_db.nim");
	nimln_(3, "toss_db.nim");
	db_pg1xfNAJINTuNjZ5I9bps6g = open_SRJkmN7JR2aulOhbafCrYA(((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_2), ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_3), ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_3), ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_3));
	nimln_(5, "toss_db.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_pg1xfNAJINTuNjZ5I9bps6g, ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_4), T1_, 0);
	nimln_(6, "toss_db.nim");
	printf("%s\012", ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_5)? (((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_5))->data:"nil");
	fflush(stdout);
	nimln_(7, "toss_db.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_pg1xfNAJINTuNjZ5I9bps6g, ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_6), T2_, 0);
	nimln_(8, "toss_db.nim");
	printf("%s\012", ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_7)? (((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_7))->data:"nil");
	fflush(stdout);
	nimln_(9, "toss_db.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_pg1xfNAJINTuNjZ5I9bps6g, ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_8), T3_, 0);
	nimln_(10, "toss_db.nim");
	printf("%s\012", ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_9)? (((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_9))->data:"nil");
	fflush(stdout);
	nimln_(11, "toss_db.nim");
	memset((void*)T4_, 0, sizeof(T4_));
	exec_kASFnJjvwTJpKpmn9aQHmPg(db_pg1xfNAJINTuNjZ5I9bps6g, ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_10), T4_, 0);
	nimln_(12, "toss_db.nim");
	printf("%s\012", ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_11)? (((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_11))->data:"nil");
	fflush(stdout);
	nimln_(14, "toss_db.nim");
	close_yRzNipQFOsKqLVySy7Je9bw_2(db_pg1xfNAJINTuNjZ5I9bps6g);
	nimln_(15, "toss_db.nim");
	printf("%s\012", ((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_12)? (((NimStringDesc*) &TM_OQVAKSQ5eImSrw9bNcanC6A_12))->data:"nil");
	fflush(stdout);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, toss_dbDatInit000)(void) {
}

